# Typical conda environment for a reproducible machine learning project
# Use `mamba env create -f environment.yml`
# or `conda env create -f environment.yml` to install the environment
# Created and maintained by garywei944(garywei944@gmail.com)

name: lm-critic
channels:
  - nvidia  # for CUDA
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pytorch  # pytorch 1.6 isn't compatible with RTX 3090
#  - pytorch=1.6.0
#  - torchvision=0.7.0
  - cudatoolkit=11.3
  - transformers=4.3.3
  - datasets=1.3.0
  - nltk
  - spacy=3.0.5
  - absl-py
  - editdistance

  # Development
  - wandb

#  # If you need to install pip packages, don't do `pip install xxx`
#  # Add the package here and run `mamba env update -f environment.yml --prune`
#  # for dependency completeness.
  - pip:
      - rouge-score